steps:
  - id: "build docker image"
    name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/admin-app-v2:dev", '--build-arg=SHOPIFY_API_SECRET=${_SHOPIFY_API_SECRET} SHOPIFY_API_KEY=${_SHOPIFY_API_KEY} SHOPIFY_APP_URL=${_SHOPIFY_APP_URL} SHOPIFY_ORDER_ISSUES_ID=${_SHOPIFY_ORDER_ISSUES_ID}', ".", "--network=cloudbuild"]
  # Push the container image to Container Registry
  - id: "upload docker image to container registry"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/admin-app-v2:dev"]
  - id: "deploy container image to cloud run"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
    - "run"
    - "deploy"
    - "admin-app-v2-dev"
    - "--image"
    - "gcr.io/$PROJECT_ID/admin-app-v2:dev"
    - "--region"
    - "europe-west3"
    - "--platform"
    - "managed"
    - "--vpc-connector"
    - "vpc-c-west3"
    - "--set-env-vars"
    - "^@^SHOPIFY_API_SECRET=${_SHOPIFY_API_SECRET}@SHOPIFY_API_KEY=${_SHOPIFY_API_KEY}@SHOPIFY_APP_URL=${_SHOPIFY_APP_URL}@SHOPIFY_ORDER_ISSUES_ID=${_SHOPIFY_ORDER_ISSUES_ID}"
    - "--allow-unauthenticated"
images:
- "gcr.io/$PROJECT_ID/admin-app-v2:dev"

